balias vi 'nvim'
balias gs 'git status'
balias ga 'git add'
balias gc 'git commit'
balias gp 'git push'
balias gb-del "git branch --merged |egrep -v '\\*|develop|master'|xargs git branch -d"
balias gch 'git checkout'
balias ll 'ls -ltrG'
balias ls 'ls -G'
balias vimr 'open -a vimr'
